// src/CodePanel.tsx
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { applyCode } from './apply';

function highlight(code: string): string {
  const esc = code.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  return esc.replace(/(\/\/.*$)|('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")|\b(function|const|let|var|if|else|for|return|new|true|false|null)\b|\b(\d+\.?\d*)\b/gm, (m, c, s, k, n) => {
    if (c) return `<span class="c">${c}</span>`;
    if (s) return `<span class="s">${s}</span>`;
    if (k) return `<span class="k">${k}</span>`;
    if (n) return `<span class="n">${n}</span>`;
    return m;
  });
}

type Status = { kind: 'synced' | 'dirty' | 'applied' | 'error'; msg?: string };

export function CodePanel({ code, onClose, avoid }: { code: string; onClose: () => void; avoid?: { x: number; y: number; w: number; h: number } }) {
  const [text, setText] = useState(code);
  const [status, setStatus] = useState<Status>({ kind: 'synced' });
  const [copied, setCopied] = useState(false);
  const focused = useRef(false);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const preRef = useRef<HTMLPreElement>(null);
  const taRef = useRef<HTMLTextAreaElement>(null);
  const codeRef = useRef(code);
  codeRef.current = code;

  // follow the graph while not editing
  useEffect(() => {
    if (!focused.current) { setText(code); setStatus({ kind: 'synced' }); }
  }, [code]);

  const apply = (t: string) => {
    const r = applyCode(t);
    setStatus(r.ok ? { kind: 'applied' } : { kind: 'error', msg: r.error });
    return r.ok;
  };
  const onChange = (t: string) => {
    setText(t);
    setStatus({ kind: 'dirty' });
    if (timer.current) clearTimeout(timer.current);
    timer.current = setTimeout(() => apply(t), 600);
  };
  const onBlur = () => {
    focused.current = false;
    if (timer.current) clearTimeout(timer.current);
    if (status.kind === 'dirty') { if (!apply(text)) return; }
    if (status.kind === 'error') return; // keep the broken text visible
    setText(codeRef.current);
    setStatus({ kind: 'synced' });
  };
  const onKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    e.stopPropagation();
    if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') { e.preventDefault(); if (timer.current) clearTimeout(timer.current); apply(text); }
    else if (e.key === 'Escape') (e.currentTarget as HTMLTextAreaElement).blur();
    else if (e.key === 'Tab') {
      e.preventDefault();
      const el = e.currentTarget;
      const s = el.selectionStart, en = el.selectionEnd;
      onChange(text.slice(0, s) + '  ' + text.slice(en));
      requestAnimationFrame(() => { el.selectionStart = el.selectionEnd = s + 2; });
    }
  };
  const sync = () => { if (preRef.current && taRef.current) { preRef.current.scrollTop = taRef.current.scrollTop; preRef.current.scrollLeft = taRef.current.scrollLeft; } };
  const html = useMemo(() => highlight(text) + '\n', [text]);

  const copy = async () => { try { await navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1200); } catch {} };
  const download = () => {
    const blob = new Blob([text], { type: 'text/javascript' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'sketch.js';
    a.click();
    URL.revokeObjectURL(a.href);
  };
  const stop = (e: React.SyntheticEvent) => e.stopPropagation();
  // dock below the preview when it sits in the right-hand column
  const style: React.CSSProperties = {};
  if (avoid && avoid.x + avoid.w > window.innerWidth - 560) { style.top = Math.min(avoid.y + avoid.h + 12, window.innerHeight - 220); style.width = Math.max(460, avoid.w); }
  return (
    <div className="codepanel" style={style} onPointerDown={stop} onDoubleClick={stop} onWheel={stop}>
      <div className="codepanel-head">
        <span className="title">sketch.js</span>
        <span className={'status ' + status.kind}>
          {status.kind === 'synced' && 'in sync · edit me'}
          {status.kind === 'dirty' && 'editing…'}
          {status.kind === 'applied' && 'applied to the patch'}
          {status.kind === 'error' && (status.msg ?? 'error')}
        </span>
        <span className="spacer" />
        <button onClick={copy}>{copied ? 'copied!' : 'copy'}</button>
        <button onClick={download}>download</button>
        <button onClick={onClose}>×</button>
      </div>
      <div className="codewrap">
        <pre ref={preRef} className="code" aria-hidden dangerouslySetInnerHTML={{ __html: html }} />
        <textarea ref={taRef} className="code codeinput" value={text} spellCheck={false} wrap="off"
          onChange={(e) => onChange(e.target.value)} onFocus={() => { focused.current = true; }} onBlur={onBlur} onKeyDown={onKeyDown} onScroll={sync} />
      </div>
    </div>
  );
}

// src/CodePanel.svelte
<script>
  import { applyCode } from './apply.js';
  import { ui } from './state.svelte.js';
  let { code, onclose } = $props();
  let text = $state(code);
  let status = $state.raw({ kind: 'synced' });
  let copied = $state(false);
  let focused = false;
  let timer = null;
  let pre = $state(null);
  let ta = $state(null);
  const stop = (e) => e.stopPropagation();

  // follow the graph while not editing
  $effect(() => {
    const c = code;
    if (!focused) { text = c; status = { kind: 'synced' }; }
  });

  function highlight(src) {
    const esc = src.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    return esc.replace(/(\/\/.*$)|('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")|\b(function|const|let|var|if|else|for|return|new|true|false|null)\b|\b(\d+\.?\d*)\b/gm, (m, c, s, k, n) => {
      if (c) return `<span class="c">${c}</span>`;
      if (s) return `<span class="s">${s}</span>`;
      if (k) return `<span class="k">${k}</span>`;
      if (n) return `<span class="n">${n}</span>`;
      return m;
    });
  }
  const html = $derived(highlight(text) + '\n');

  function apply(t) {
    const r = applyCode(t);
    status = r.ok ? { kind: 'applied' } : { kind: 'error', msg: r.error };
    return r.ok;
  }
  function onInput(e) {
    text = e.target.value;
    status = { kind: 'dirty' };
    clearTimeout(timer);
    timer = setTimeout(() => apply(text), 600);
  }
  function onBlur() {
    focused = false;
    clearTimeout(timer);
    if (status.kind === 'dirty' && !apply(text)) return;
    if (status.kind === 'error') return; // keep the broken text visible
    text = code;
    status = { kind: 'synced' };
  }
  function onKey(e) {
    e.stopPropagation();
    if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') { e.preventDefault(); clearTimeout(timer); apply(text); }
    else if (e.key === 'Escape') e.currentTarget.blur();
    else if (e.key === 'Tab') {
      e.preventDefault();
      const el = e.currentTarget;
      const s = el.selectionStart, en = el.selectionEnd;
      text = text.slice(0, s) + '  ' + text.slice(en);
      status = { kind: 'dirty' };
      clearTimeout(timer);
      timer = setTimeout(() => apply(text), 600);
      requestAnimationFrame(() => { el.selectionStart = el.selectionEnd = s + 2; });
    }
  }
  function sync() { if (pre && ta) { pre.scrollTop = ta.scrollTop; pre.scrollLeft = ta.scrollLeft; } }
  async function copy() { try { await navigator.clipboard.writeText(text); copied = true; setTimeout(() => (copied = false), 1200); } catch {} }
  function download() {
    const blob = new Blob([text], { type: 'text/javascript' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'sketch.js';
    a.click();
    URL.revokeObjectURL(a.href);
  }
  // dock below the preview when it sits in the right-hand column
  const dock = $derived.by(() => {
    const a = ui.previewRect;
    if (a && a.x + a.w > window.innerWidth - 560) return `top: ${Math.min(a.y + a.h + 12, window.innerHeight - 220)}px; width: ${Math.max(460, a.w)}px`;
    return '';
  });
</script>

<div class="codepanel" style={dock} onpointerdown={stop} ondblclick={stop} onwheel={stop}>
  <div class="codepanel-head">
    <span class="title">sketch.js</span>
    <span class="status {status.kind}">
      {#if status.kind === 'synced'}in sync · edit me{:else if status.kind === 'dirty'}editing…{:else if status.kind === 'applied'}applied to the patch{:else}{status.msg ?? 'error'}{/if}
    </span>
    <span class="spacer"></span>
    <button onclick={copy}>{copied ? 'copied!' : 'copy'}</button>
    <button onclick={download}>download</button>
    <button onclick={onclose}>×</button>
  </div>
  <div class="codewrap">
    <pre bind:this={pre} class="code" aria-hidden="true">{@html html}</pre>
    <textarea bind:this={ta} class="code codeinput" value={text} spellcheck="false" wrap="off"
      oninput={onInput} onfocus={() => { focused = true; }} onblur={onBlur} onkeydown={onKey} onscroll={sync}></textarea>
  </div>
</div>
