// src/canvas/GroupView.svelte
<script>
  import { updateGroup } from '../store.js';
  let { group, x, y, selected } = $props();
  let editing = $state(false);
  let text = $state('');
  const stop = (e) => e.stopPropagation();
  const autofocus = (el) => el.focus();
</script>

<div class="group" class:selected data-group={group.id}
  style:left="{x}px" style:top="{y}px" style:width="{group.w}px" style:height="{group.h}px" style:border-color={group.color} style:background={group.color + '14'}>
  <div class="group-head" data-group-header={group.id} style:background={group.color}>
    {#if editing}
      <input use:autofocus bind:value={text} data-widget
        onblur={() => { editing = false; if (text.trim()) updateGroup(group.id, { name: text.trim() }); }}
        onkeydown={(e) => { e.stopPropagation(); if (e.key === 'Enter') e.target.blur(); if (e.key === 'Escape') editing = false; }}
        onpointerdown={stop} />
    {:else}
      <span ondblclick={(e) => { e.stopPropagation(); text = group.name; editing = true; }}>{group.name}</span>
    {/if}
  </div>
  <span class="resize" data-resize={group.id}></span>
</div>

// src/canvas/GroupView.tsx
import React, { memo, useState } from 'react';
import type { GroupData } from '../types';
import { updateGroup } from '../store';

export const GroupView = memo(function GroupView({ group, x, y, selected }: { group: GroupData; x: number; y: number; selected: boolean }) {
  const [editing, setEditing] = useState(false);
  const [text, setText] = useState(group.name);
  return (
    <div className={'group' + (selected ? ' selected' : '')} data-group={group.id}
      style={{ left: x, top: y, width: group.w, height: group.h, borderColor: group.color, background: group.color + '14' }}>
      <div className="group-head" data-group-header={group.id} style={{ background: group.color }}>
        {editing ? (
          <input autoFocus value={text} data-widget onChange={(e) => setText(e.target.value)}
            onBlur={() => { setEditing(false); if (text.trim()) updateGroup(group.id, { name: text.trim() }); }}
            onKeyDown={(e) => { e.stopPropagation(); if (e.key === 'Enter') (e.target as HTMLInputElement).blur(); if (e.key === 'Escape') setEditing(false); }}
            onPointerDown={(e) => e.stopPropagation()} />
        ) : (
          <span onDoubleClick={(e) => { e.stopPropagation(); setText(group.name); setEditing(true); }}>{group.name}</span>
        )}
      </div>
      <span className="resize" data-resize={group.id} />
    </div>
  );
});
